
class Display:
    #make a GUI with the following elements
    #Top box is an input box that can
    #   1. display the mnemonic phrase generated by the user
    #   2. have the user input a memonic phrase
    #Bottom left will have 2 buttons
    #   1. one button to start collecting entropy
    #   2. one button to generate mnemonic phrase and key
    #Bottom right will have a display showing master key
    def __init__(self):
        self.hashing_functions = HashingFunctions()
        self.win1 = tk.Tk()
        self.win1.wm_title('Mnemonic Phrase Generator')
        self.win1.resizable(width=False, height=False)
        self.mnemonicLabel = tk.Label(self.win1, text = 'Mnemonic Phrase')
        self.mnemonicBox = tk.Text(self.win1, height=5)
        self.keyLabel = tk.Label(self.win1, text = 'private_key')
        self.keyBox = tk.Text(self.win1, height=5)
        pass

    def user_provided_entropy(self):
        ent = rand.randrange(1,10**256-1)
        self.hashing_functions.entropy = str(ent)
        check_sum = self.hashing_functions.check_sum()
        mnemonic = self.create_word_list()
        mnemonic = ' '.join()
        self.keyBox.delete('1.0', tk.END)
        self.mnemonicBox.delete('1.0', tk.END)
        self.mnemonicBox.insert('1.0', mnemonic)
        mnemonic = self.mnemonicBox.get('1.0', tk.END)
        key = self.create_master_key(mnemonic)
        self.keyBox.insert('1.0', key)

    def user_provided_mnemonic(self):
        mnemonic = self.mnemonicBox.get('1.0', tk.END)
        print(type(mnemonic))
        key = self.create_master_key(mnemonic)
        self.keyBox.delete('1.0', tk.END)
        self.keyBox.insert('1.0', key)

    def create_buttons(self):
        self.entropyButton = tk.Button(self.win1, text = 'create mnemonic phrase', command = self.user_provided_entropy) #add command from hash class
        self.generateButton = tk.Button(self.win1, text = 'create bitcoin address', command = self.user_provided_mnemonic) #add create_word_list function


    def main_window(self):
        self.label = tk.Label(self.win1, text='entropy')
        self.entry = tk.Entry(self.win1, bd=5)

    def window_elements(self):
        self.mnemonicLabel.grid(row=0, column=1, columnspan=2)
        self.mnemonicBox.grid(column=1, columnspan=2, row=1, padx=10, pady=10)
        self.keyBox.grid(column=1, columnspan=2, row=1, padx=10, pady=10)
        self.entropyButton.grid(column=1, row=2)
        self.generateButton.grid(column =2, row = 2)
        self.keyLabel.grid(column=1, columnspan=2, row=3)
        self.keyBox.grid(column=1, columnspan=2, row=4)

    def display_window(self):
        self.create_buttons()
        self.main_window()
        self.window_elements()
        self.win1.mainloop()

if  __name__ == '__main__':

    Display().display_window()
